models.py
#!/usr/bin/env python
__author__ = 'XeanYu'
from exts import db
from flask_login import UserMixin
from exts import login_manager
from func.date import now


# Log Users [用户数据]
class Users(db.Model,UserMixin):
    __tablename__ = 'users'

    uid = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64),unique=True,nullable=False,index=True)
    password = db.Column(db.String(124),nullable=False,index=True)
    mail = db.Column(db.String(124),index=True,nullable=False)
    code = db.Column(db.String(40),nullable=False) # 私密代码
    sgin_up_date = db.Column(db.String(64)) # 登录时间
    login_static = db.Column(db.String(1),default='0') # 是否可以登录
    vip = db.Column(db.String(64),default=0) # 是否是VIP

    # 表中没有id字段，自己定义返回uid字段
    def get_id(self):
        return self.uid

@login_manager.user_loader
def user_load(id):
    return Users.query.get(id)

# Login log [登录日志]
class Login_logs(db.Model):
    __tablename__ = 'login_logs'

    id = db.Column(db.Integer,primary_key=True) # id => 主键
    username = db.Column(db.String(64),index=True) # 用户的用户名
    browser = db.Column(db.String(124),index=True) # 用户使用的浏览器
    device = db.Column(db.String(124),index=True)  # 用户使用的设备
    os = db.Column(db.String(124),index=True)  # 用户的操作系统
    ip = db.Column(db.String(64),index=True) # 用户IP地址
    platform = db.Column(db.String(12),index=True) # user's platform
    login_date = db.Column(db.String(64),default=now()) # 登录时间

class Site(db.Model):
    __tablename__ = 'site_config'

    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(124),index=True)
    title = db.Column(db.String(124),index=True)
    keywords = db.Column(db.String(246),index=True)
    description = db.Column(db.String(1024),index=True)

class Api(db.Model):
    __tablename__ = 'apis'

    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(124)) # API名称
    api = db.Column(db.String(1024)) # API

class Vip(db.Model):
    __tablename__ = 'vips'

    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(124),nullable=False,unique=True)
    attack_num = db.Column(db.Integer,nullable=False)
    max_use_time = db.Column(db.Integer,nullable=False)
    yuan = db.Column(db.Integer)
    pay_url = db.Column(db.String(520),default='#')

class Placard(db.Model):
    __tablename__ = 'placards'

    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(124),nullable=False)
    text = db.Column(db.String(1024))
    author = db.Column(db.String(64))
    date = db.Column(db.String(124),default=now())

class Message(db.Model):
    __tablename__ = 'messages'

    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(124),nullable=False)
    text = db.Column(db.Text)
    user = db.Column(db.String(64))
    say_date = db.Column(db.String(124),default=now())
    look_date = db.Column(db.String(124),default='none')
    is_look = db.Column(db.Boolean,default=False)

class Card(db.Model):
    __tablename__ = 'cards'

    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(124),nullable=False)
    vip_id = db.Column(db.Integer)
    card = db.Column(db.String(246),index=True)
    is_use = db.Column(db.Boolean,default=False)
    time = db.Column(db.String(124))
    use_date = db.Column(db.String(124))
    use_user = db.Column(db.String(64))
    make_date = db.Column(db.String(124),default=now())

templates/getpass.html
<!DOCTYPE html>
<!--author: XeanYu -->
<!-- 密码找回页面 -->
<html>

<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <title>密码找回</title>

  <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='style/getpass.css') }}">
  <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>

</head>

<body>
  <div class="container">
      <div class="row">
      <div class="col-lg-10 col-lg-push-1 getpass">

    <!--输入栏盒子-->
        <div class="box">

        <div class='box_title'>
            <h3 class="text-center page-header">密码找回</h3>
        </div>
            <!--input user's username-->
            <div class="user col-lg-8 col-lg-push-2">
            <form method="post" id="form" action="{{ url_for('main.getpass') }}">

            <p class="input-title">用户名</p>
            <div class="input-group input">
                <span class="input-group-addon"><span class="glyphicon glyphicon glyphicon-search"></span></span>
                <input type="text" name="user" id="username_input" class="form-control" placeholder="请输入您的用户名" required="required"/>
            </div>

            <p class="input-title">私密代码</p>
            <div class="input-group input find">
                <span class="input-group-addon"><span class="glyphicon glyphicon-console"></span></span>
                <input type="text" name="code" id="username_input" class="form-control" placeholder="请输入您私密代码" required="required"/>
            </div>

            <p class="input-title">新密码</p>
            <div class="input-group input find">
                <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                <input type="text" name="newpass" id="username_input" class="form-control" placeholder="新密码" required="required"/>
            </div>

                <div class="alert alert-danger" id="alert-box">
                    <span class="info glyphicon glyphicon-info-sign" id="info"></span>
                    <span class="off glyphicon glyphicon-remove-circle" id="off"></span>
                </div>

            <div class="input-group input find submit">
                <button class="btn btn-danger">立即修改</button>
            </div>

            </form>
            </div>
        </div>
    </div>

    </div>
  </div>
<script type="text/javascript" src="{{ url_for('static',filename='exts_js/getpass.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/canvas-nest.js') }}"></script>
</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="{{ seo.keywords }}">
    <meta name="description" content="{{ seo.description }}">
    <title>{{ seo.title }}</title>
</head>
<body>

</body>
</html>

templates/os_api.html
<style>
    .of {margin-top: 20px;}
</style>

<div class="mdui-container doc-container">
    <!--  -->
    <div class="of">
        <h1 class="doc-title mdui-text-color-red">API管理</h1>
    </div>

    <div class="mdui-divider"></div>
    <h3><strong>API管理</strong></h3>



</div>

templates/os_logs.html
<style>
    .of {margin-top: 20px;}

</style>
<!-- Sweetalert CSS file -->
<div class="mdui-container doc-container">
    <div class="of">
        <h1 class="doc-title mdui-text-color-theme">日志管理</h1>
    </div>

    <div>
        <!-- 平台配置 -->
        <div class="mdui-divider"></div>
        <h3><kbd><strong>Logs</strong></kbd></h3>
    </div>

</div>

templates/os_placard.html
<style>
    .of {margin-top: 20px;}
</style>

<div class="mdui-container doc-container">
    <!--  -->
    <div class="of">
        <h1 class="doc-title mdui-text-color-red">公告管理</h1>
    </div>

    <div class="mdui-divider"></div>
    <h3><strong>公告</strong></h3>

    <form action="{{ url_for('main.placard') }}" method="post" id="placard">

        <div class="mdui-textfield">
            <i class="mdui-icon material-icons">title</i>
            <label class="mdui-textfield-label">标题</label>
            <input class="mdui-textfield-input" type="text" value="" name="title" required="required"/>
        </div>

        <div class="mdui-textfield">
            <i class="mdui-icon material-icons">text_fields</i>
            <label class="mdui-textfield-label">公告内容</label>
            <input class="mdui-textfield-input" type="text" value="" name="text"/>
        </div>


        <br>
        <div class="mdui-float-right">
            <button class="mdui-fab mdui-color-theme-accent mdui-ripple"><i class="mdui-icon material-icons">create</i></button>
        </div>
    </form>

    <div class="mdui-divider"></div>

    <div class="row of">
        <h3 class="page-header">PlaCards</h3>
        <div class="mdui-table-fluid">
            <table class="mdui-table">
            <thead>
              <tr>
                <th>标题</th>
                <th>内容</th>
                <th>作者</th>
                <th>日期</th>
                <th>#</th>
              </tr>
            </thead>
            <tbody id="tbody">
            <!-- For循环服务器 -->
              {% for placard in placards %}

                <tr class="{{ placard.title }}">
                    <td>{{ placard.title }}</td>
                    <td>{{ placard.text }}</td>
                    <td>{{ placard.author }}</td>
                    <td>{{ placard.date }}</td>
                    <td><button class="delplacard del mdui-btn mdui-btn-raised mdui-ripple" id="{{ placard.title }}">Delete</button></td>
                </tr>

              {% endfor %}

            </tbody>
          </table>
        </div>

    </div>
    <hr>
    <br>
<script src="{{ url_for('static',filename='exts_js/placard_set.js') }}" type="text/javascript"></script>
</div>

templates/os_say.html
<style>
    .of {margin-top: 20px;}
</style>
<div class="mdui-container doc-container">
    <!-- title -->
    <div class="of">
        <h1 class="doc-title mdui-text-color-red">留言处理</h1>
    </div>

    <div class="mdui-divider"></div>
    <h3><strong>留言</strong></h3>
    <hr>
    <div>
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h1 class="panel-title"><strong>留言管理</strong></h1>
          </div>


          <div class="panel-body row" id="body">
          {% for say in says %}
              <div class="col-lg-5 col-lg-push-1" id="{{ say.id }}">
                <div class="panel panel-info">
                    <!-- 标题 -->
                    <div class="panel-heading">
                          <h3 class="panel-title" id="title">
                              <strong class="text-left">{{ say.title }}</strong>
                              {% if say.is_look %}
                                <span class="title label label-success mdui-float-right"> 已被浏览 </span>
                              {% else %}
                                <span class="title label label-danger mdui-float-right"> 未被浏览 </span>
                              {% endif %}
                            <strong class=""><span class="label label-success mdui-text-color-purple"> {{ say.user }} </span></strong>
                          </h3>
                    </div>
                      <!-- 身体 -->

                      <div class="panel-body" id="pbody">
                        <strong class="text-success">{{ say.text }}</strong>
                        {% if not say.is_look %}
                          <span class="body label label-info text-right ">发布于 {{ say.say_date }}</span>
                        {% else %}
                          <span class="body label label-primary text-right" >被查看于 {{ say.look_date }}</span>
                          {% endif %}
                        <button type="button" class="submit btn btn-info" style="float: right" id="{{ say.id }}"><strong>读</strong></button>
                      </div>
                </div>
              </div>
          {% endfor %}
          </div>

        </div>
    </div>
<script src="{{ url_for('static',filename='exts_js/os_say.js') }}" type="text/javascript"></script>
</div>

templates/os_set.html
<style>
    .of {margin-top: 20px;}
</style>

<!-- 平台管理 -->
<div class="mdui-container doc-container">
    <div class="of">
        <h1 class="doc-title mdui-text-color-red">平台管理</h1>
    </div>

    <div>
        <!-- 平台配置 -->
        <div class="mdui-divider"></div>
        <h3><kbd><strong>首页 SEO</strong></kbd> </h3>

        <form action="{{ url_for('main.os_set') }}" method="post" id="os_form">

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">account_balance</i>
                <label class="mdui-textfield-label">平台名称</label>
                <input class="mdui-textfield-input" type="text" value="{{ seo.name }}" name="name" required="required"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">title</i>
                <label class="mdui-textfield-label">首页标题 【 title 】</label>
                <input class="mdui-textfield-input" type="text" value="{{ seo.title }}" name="title" required="required"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">location_searching</i>
                <label class="mdui-textfield-label">首页关键字 【 keywords 】 <small>请用英文状态下的逗号进行分割</small></label>
                <input class="mdui-textfield-input" type="text" value="{{ seo.keywords }}" name="keywords" required="required"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">description</i>
                <label class="mdui-textfield-label">首页描述 【 description 】</label>
                <input class="mdui-textfield-input" type="text" value="{{ seo.description }}" name="description" required="required"/>
            </div>

            <br>
            <div class="mdui-float-right">
                <button class="mdui-fab mdui-color-theme-accent mdui-ripple"><i class="mdui-icon material-icons">create</i></button>
            </div>
        </form>

    </div>

</div>
<script type="text/javascript" src="{{ url_for('static',filename='exts_js/change_os.js') }}"></script>

templates/os_vip.html
<style>
    .of {margin-top: 20px;}
</style>
<script type="text/javascript" src="{{ url_for('static',filename='exts_js/del_vip.js') }}"></script>
<div class="mdui-container doc-container">
    <!-- title -->
    <div class="of">
        <h1 class="doc-title mdui-text-color-red">套餐 SET</h1>
    </div>

    <div class="mdui-divider"></div>
    <h3><strong>套餐管理</strong></h3>

    <form action="{{ url_for('main.vip_set') }}" method="post" id="vip">

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">account_balance</i>
                <label class="mdui-textfield-label">套餐名称 (不可以和其他套餐重复,如果名称重复,则自动修改)</label>
                <input class="mdui-textfield-input" type="text" value="" name="name" required="required" id="name"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">format_list_numbered</i>
                <label class="mdui-textfield-label">压测次数 /Day</label>
                <input class="mdui-textfield-input" type="number" value="" name="attack_num" required="required" id="attack_num"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">attach_money</i>
                <label class="mdui-textfield-label">价格 (RMB)</label>
                <input class="mdui-textfield-input" type="number" value="" name="yuan" required="required" id="yuan"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">access_time</i>
                <label class="mdui-textfield-label">压测最大时间 (S)</label>
                <input class="mdui-textfield-input" type="number" value="" name="use_time" required="required" id="use_time"/>
            </div>

            <div class="mdui-textfield">
                <i class="mdui-icon material-icons">http</i>
                <label class="mdui-textfield-label">套餐购买链接</label>
                <input class="mdui-textfield-input" type="url" value="" name="pay_url" required="required" id="pay_url"/>
            </div>

            <br>
            <div class="mdui-float-right">
                <button class="mdui-fab mdui-color-theme-accent mdui-ripple"><i class="mdui-icon material-icons">create</i></button>
            </div>
    </form>

    <div class="mdui-divider"></div>

    <div class="row of">
        <h3 class="page-header">VIP</h3>
        <div class="mdui-table-fluid">
            <table class="mdui-table">
            <thead>
              <tr>
                <th>编号</th>
                <th>压测次数 \Day</th>
                <th>压测最大时间 (S)</th>
                <th>价格 (RMB)</th>
                <th>购买链接</th>
                <th>#</th>
              </tr>
            </thead>
            <tbody id="tbody">
            <!-- For循环服务器 -->
              {% for vip in vips %}

                <tr class="{{ vip.name }}">
                    <td>{{ vip.name }}</td>
                    <td>{{ vip.attack_num }}</td>
                    <td>{{ vip.max_use_time }}</td>
                    <td>{{ vip.yuan }}</td>
                    <td><a href="{{ vip.pay_url }}"><i class="mdui-icon material-icons">add_shopping_cart</i></a></td>
                    <td><button class="del mdui-btn mdui-btn-raised mdui-ripple" id="{{ vip.name }}">Delete</button></td>
                </tr>

              {% endfor %}

            </tbody>
          </table>
        </div>

    </div>
    <hr>
    <br>

<script src="{{ url_for('static',filename='exts_js/vip_set.js') }}" type="text/javascript" language="JavaScript"></script>

</div>

templates/sgin_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--登录页面 sgin_in-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>登录</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static',filename='style/sgin.css') }}" />
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
</head>
<body>
    <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
            <div class="sgin login_temp">
            <h3 class="page-header text-center size">
                <t><a href="{{ url_for('main.sgin_in') }}" class="action a">登录&nbsp;</a></t>
                <b>·</b>
                <t><a href="{{ url_for('main.sgin_up') }}" class="a login">&nbsp;注册</a></t>
            </h3>

            <div>
                <form class="form" action="{{ url_for('main.sgin_in') }}" method="post" accept-charset="UTF-8" id="user_info">

                    <div class="input">
                        <span class="glyphicon glyphicon-user"></span>
                        <input type="text" class="input_user" placeholder="用户名" name="username" required="required"/>
                    </div>

                    <div class="input">
                        <span class="glyphicon glyphicon-lock"></span>
                        <input type="password" class="input_user" placeholder="密码" name="password" required="required"/>
                        <div class="text-danger sgin_pass"><strong></strong></div>
                    </div>

                     <div>
                        <p class="text-danger" id="alert"></p>

                        <co class="code">随机码 ==> <bg class="text-danger">{{ num_code }}</bg></co>
                        <div class="input code_box">
                            <span class="glyphicon glyphicon-triangle-right"></span>
                            <input type="text" class="input_user" placeholder="随机码" name="random_code" required="required"/>
                        </div>
                     </div>
                        <button class="sgin_btn btn btn-danger btn-block">登 录</button>
                    <p class="text-danger p"><strong><a href="{{ url_for('main.getpass') }}">忘记密码?</a></strong></p>

                </form>

            </div>
        </div></div>
    </div>
    <script type="text/javascript" src="{{ url_for('static',filename='exts_js/sgin_in.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/canvas-nest.js') }}"></script>
</body>
</html>

templates/user.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{{ url_for('static',filename='mdui/css/mdui.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/sweetalert.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='style/user.css') }}">
    <script type="text/javascript" src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/sweetalert.min.js') }}"></script>
    <title>控制台</title>
</head>
<body class="mdui-drawer-body-left mdui-appbar-with-toolbar mdui-theme-primary-blue mdui-theme-accent-pink mdui-theme-layout-dark mdui-loaded">

<!-- 导航条 -->
<header class="mdui-appbar mdui-appbar-fixed">
  <div class="mdui-toolbar mdui-color-theme">
    <span class="mdui-btn mdui-btn-icon mdui-ripple mdui-ripple-white" mdui-drawer="{target: '#main-drawer', swipe: true}"><i class="mdui-icon material-icons">menu</i></span>
    <a href="./" class="mdui-typo-headline mdui-hidden-xs"><i class="mdui-icon material-icons">&#xe894;</i></a>
        <div class="mdui-toolbar-spacer"></div>
    <span class="mdui-btn mdui-btn-icon mdui-ripple mdui-ripple-white">T</span>
  </div>
</header>

<!-- 侧栏 -->
<div class="mdui-drawer" id="main-drawer">
    <style>
        a {text-decoration:none;color: #fff;}
        a:hover{text-decoration:none;color: #fff;}
        a:link{text-decoration:none;color: #fff;}
    </style>
  <div class="mdui-list" mdui-collapse="{accordion: true}" style="margin-bottom: 76px;">

      <a href="{{ url_for('main.console') }}">
    <div class="mdui-collapse-item ">
      <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-blue">near_me</i>
        <div class="mdui-list-item-content">导航</div>

      </div>
    </div></a>

     <a href="{{ url_for('main.self') }}">
    <div class="mdui-collapse-item ">
      <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-deep-orange">perm_identity</i>
        <div class="mdui-list-item-content">您的资料</div>
      </div>
    </div></a>

    <div class="mdui-collapse-item ">
    <div class="mdui-collapse-item mdui-collapse-item-open">
      <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-green">tune</i>
        <div class="mdui-list-item-content">压测面板</div>

      </div>
    </div>
    </div>

      <div class="mdui-collapse-item ">
    <div class="mdui-collapse-item mdui-collapse-item-open">
        <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-orange">list</i>
            <div class="mdui-list-item-content">压测记录</div>
        </div>
    </div>
    </div>

    <div class="mdui-collapse-item ">
      <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-brown">add_shopping_cart</i>
        <div class="mdui-list-item-content">购买套餐</div>

      </div>
    </div>


    <div class="mdui-collapse-item ">
        <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-blue-grey">search</i>
        <div class="mdui-list-item-content">端口扫描</div>
      </div>
    </div>

      <a href="{{ url_for('main.say') }}">
      <div class="mdui-collapse-item ">
        <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
        <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-red">add</i>
        <div class="mdui-list-item-content">Say</div>
      </div>
    </div>
      </a>

      <div class="mdui-collapse-item ">
          <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-purple">local_mall</i>
            <div class="mdui-list-item-content">API接口</div>
          </div>
      </div>
      {% if admin %}

          <a href="{{ url_for('main.os_set') }}">
          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">settings</i>
            <div class="mdui-list-item-content">系统管理</div>
            </div>
          </div>
          </a>


          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">people</i>
            <div class="mdui-list-item-content">用户管理</div>
            </div>
          </div>

          <a href=>
          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">assignment</i>
            <div class="mdui-list-item-content">日志管理</div>
            </div>
          </div>
          </a>

          <a href="{{ url_for('main.vip_set') }}">
          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">shop</i>
            <div class="mdui-list-item-content">套餐管理</div>
            </div>
          </div>
          </a>

          <a href="{{ url_for('main.make_card') }}">
          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">credit_card</i>
            <div class="mdui-list-item-content">卡密生成</div>
            </div>
          </div></a>

          <a href="{{ url_for('main.os_say') }}">
          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">announcement</i>
            <div class="mdui-list-item-content">留言处理</div>
            </div>
          </div></a>

          <a href="{{ url_for('main.placard') }}">
          <div class="mdui-collapse-item ">
            <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-teal">border_color</i>
            <div class="mdui-list-item-content">公告</div>
            </div>
          </div>
          </a>
      {% endif %}

      <a href="{{ url_for('main.logout') }}">
      <div class="mdui-collapse-item ">
          <div class="mdui-collapse-item-header mdui-list-item mdui-ripple">
            <i class="mdui-list-item-icon mdui-icon material-icons mdui-text-color-purple">exit_to_app</i>
            <div class="mdui-list-item-content">退出登录</div>
          </div>
      </div>
      </a>

  </div>
</div>

{% include template %}
<script src="{{ url_for('static',filename='js/mdui.min.js') }}" type="text/javascript"></script>
</body>
</html>